ERROR:root:Scanning 2561.jpg failed: 
Traceback (most recent call last):
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 71, in main
    draw_boxes_on_image(reader, root + '/' + filename, out_dir)
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 29, in draw_boxes_on_image
    bounds = reader.readtext(in_path)
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 384, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 281, in detect
    text_box = get_textbox(self.detector, img, canvas_size, mag_ratio,\
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 81, in get_textbox
    bboxes, polys = test_net(canvas_size, mag_ratio, detector, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 38, in test_net
    y, feature = net(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\craft.py", line 60, in forward
    sources = self.basenet(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\model\modules.py", line 61, in forward
    h = self.slice1(X)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "C:\Python39\lib\site-packages\torch\nn\functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 4.00 GiB total capacity; 1.47 GiB already allocated; 824.35 MiB free; 2.03 GiB reserved in total by PyTorch)
ERROR:root:Scanning 2794.jpg failed: 
Traceback (most recent call last):
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 71, in main
    draw_boxes_on_image(reader, root + '/' + filename, out_dir)
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 29, in draw_boxes_on_image
    bounds = reader.readtext(in_path)
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 384, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 281, in detect
    text_box = get_textbox(self.detector, img, canvas_size, mag_ratio,\
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 81, in get_textbox
    bboxes, polys = test_net(canvas_size, mag_ratio, detector, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 38, in test_net
    y, feature = net(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\craft.py", line 60, in forward
    sources = self.basenet(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\model\modules.py", line 61, in forward
    h = self.slice1(X)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "C:\Python39\lib\site-packages\torch\nn\functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 4.00 GiB total capacity; 1.47 GiB already allocated; 842.35 MiB free; 2.01 GiB reserved in total by PyTorch)
ERROR:root:Scanning 2805.jpg failed: 
Traceback (most recent call last):
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 71, in main
    draw_boxes_on_image(reader, root + '/' + filename, out_dir)
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 29, in draw_boxes_on_image
    bounds = reader.readtext(in_path)
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 384, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 281, in detect
    text_box = get_textbox(self.detector, img, canvas_size, mag_ratio,\
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 81, in get_textbox
    bboxes, polys = test_net(canvas_size, mag_ratio, detector, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 38, in test_net
    y, feature = net(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\craft.py", line 60, in forward
    sources = self.basenet(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\model\modules.py", line 61, in forward
    h = self.slice1(X)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "C:\Python39\lib\site-packages\torch\nn\functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 4.00 GiB total capacity; 1.47 GiB already allocated; 842.35 MiB free; 2.01 GiB reserved in total by PyTorch)
ERROR:root:Scanning 2814.jpg failed: 
Traceback (most recent call last):
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 71, in main
    draw_boxes_on_image(reader, root + '/' + filename, out_dir)
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 29, in draw_boxes_on_image
    bounds = reader.readtext(in_path)
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 384, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 281, in detect
    text_box = get_textbox(self.detector, img, canvas_size, mag_ratio,\
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 81, in get_textbox
    bboxes, polys = test_net(canvas_size, mag_ratio, detector, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 38, in test_net
    y, feature = net(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\craft.py", line 60, in forward
    sources = self.basenet(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\model\modules.py", line 61, in forward
    h = self.slice1(X)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "C:\Python39\lib\site-packages\torch\nn\functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 4.00 GiB total capacity; 1.47 GiB already allocated; 842.35 MiB free; 2.01 GiB reserved in total by PyTorch)
ERROR:root:Scanning 564.jpg failed: 
Traceback (most recent call last):
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 71, in main
    draw_boxes_on_image(reader, root + '/' + filename, out_dir)
  File "C:\Users\Tobi\Projects\Development\MapScanner\scan_maps.py", line 29, in draw_boxes_on_image
    bounds = reader.readtext(in_path)
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 384, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Python39\lib\site-packages\easyocr\easyocr.py", line 281, in detect
    text_box = get_textbox(self.detector, img, canvas_size, mag_ratio,\
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 81, in get_textbox
    bboxes, polys = test_net(canvas_size, mag_ratio, detector, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
  File "C:\Python39\lib\site-packages\easyocr\detection.py", line 38, in test_net
    y, feature = net(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\craft.py", line 60, in forward
    sources = self.basenet(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\easyocr\model\modules.py", line 61, in forward
    h = self.slice1(X)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "C:\Python39\lib\site-packages\torch\nn\functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.49 GiB (GPU 0; 4.00 GiB total capacity; 1.84 GiB already allocated; 480.35 MiB free; 2.37 GiB reserved in total by PyTorch)
